# Generated by Django 2.2.1 on 2021-04-07 06:20

from django.db import migrations, models
import lib.objectid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(default=lib.objectid.create_objectid, max_length=24, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('college_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='高考分数')),
                ('area', models.CharField(max_length=5, verbose_name='地区')),
                ('particular_year', models.PositiveIntegerField(verbose_name='高考年份')),
            ],
        ),
    ]
