# Generated by Django 2.2.1 on 2021-04-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[(0, '普通用户'), (1, 'vip用户'), (2, 'svip用户')], default=0, max_length=1),
        ),
    ]
