# Generated by Django 2.2.1 on 2021-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_role',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'vip用户'), (2, 'svip用户')], default=0, max_length=1),
        ),
    ]
