# Generated by Django 2.2.1 on 2021-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210409_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='college_score',
            field=models.CharField(max_length=6, verbose_name='高考分数'),
        ),
    ]
