# Generated by Django 2.2.1 on 2021-04-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210409_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'vip用户'), (2, 'svip用户')], default=0, verbose_name='用户权限'),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_user',
        ),
    ]
